### ISSUE TITLE
Error using Mooncats::Image.mint() with more than one parameter

### ISSUE THREAD

**Issue by thomasoss** [cryptocopycats/programming-mooncats#1]
Hello
with
Mooncats::Image.mint( '0x00000800fa', zoom: 2 ).save( 'i/mooncat-00000800fa_x2.png' )
I get an error:
1: from mint.rb:54:in `<main>'
/Users/xck2025/.gem/ruby/2.7.2/gems/mooncats-1.1.1/lib/mooncats/image.rb:12:in `generate': wrong number of arguments (given 2, expected 1) (ArgumentError)

I rewrote the code in mint.rb to
args=["--zoom","2","--dir","i","0x00000800fa","0x0077c8278d","0xff5f000ca7"]
Mooncats.main(args)

args=["--zoom","4","--dir","i","0x00000800fa","0x0077c8278d","0xff5f000ca7"]
Mooncats.main(args)

args=["--zoom","8","--dir","i","0x00000800fa","0x0077c8278d","0xff5f000ca7"]
Mooncats.main(args)

This does work for me
Environment: Mac OS Monterey 12.0.1
ruby startet from command line (ruby mint.rb)
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin20]

Maybe this can help others that have the same problem

**Comment by geraldb** [comment]
Thanks for reporting. I unified / simplified the (pixel art) image class. The script needs to get updated - zoom is now a method and no longer an optional argument:

    Mooncats::Image.mint( '0x00000800fa', zoom: 2 ).save( 'i/mooncat-00000800fa_x2' )

Change to:

    Mooncats::Image.mint( '0x00000800fa' ).zoom( 2 ).save( 'i/mooncat-00000800fa_x2' )    # or
    Mooncats::Image.generate( '0x00000800fa' ).zoom( 2 ).save( 'i/mooncat-00000800fa_x2' )

**Comment by thomasoss** [comment]
Thank you ;-)
